"""empty message

Revision ID: 2bac1d3e896d
Revises: e58c00d4a7c4
Create Date: 2022-11-28 15:28:38.723728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bac1d3e896d'
down_revision = 'e58c00d4a7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('school_type')
        batch_op.drop_column('school_status')
        batch_op.drop_column('school_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_password', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school_type', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
