"""empty message

Revision ID: 569c7c4b0242
Revises: ced53e17ebc3
Create Date: 2022-11-28 15:14:52.539652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569c7c4b0242'
down_revision = 'ced53e17ebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('school_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('school_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('school_status')
        batch_op.drop_column('school_type')
        batch_op.drop_column('school_password')

    # ### end Alembic commands ###
