"""empty message

Revision ID: 836b5839fd10
Revises: 569c7c4b0242
Create Date: 2022-11-28 15:22:17.800993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836b5839fd10'
down_revision = '569c7c4b0242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('school_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_password', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
