"""empty message

Revision ID: 94f11f037666
Revises: 9f185410c6fc
Create Date: 2022-11-28 15:07:38.995803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f11f037666'
down_revision = '9f185410c6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('school_type')
        batch_op.drop_column('school_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_password', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('school_type', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
