"""empty message

Revision ID: 98e799489c08
Revises: af4c6977b513
Create Date: 2022-12-13 15:37:17.236008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e799489c08'
down_revision = 'af4c6977b513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_course', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('teacher_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('teacher_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('teacher_status')
        batch_op.drop_column('teacher_type')
        batch_op.drop_column('teacher_course')

    # ### end Alembic commands ###
