"""empty message

Revision ID: a14f704522ad
Revises: 2bac1d3e896d
Create Date: 2022-11-28 15:28:59.920872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14f704522ad'
down_revision = '2bac1d3e896d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_password', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('school_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('school_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('school_status')
        batch_op.drop_column('school_type')
        batch_op.drop_column('school_password')

    # ### end Alembic commands ###
